name: Setup App Token
description: Mint a GitHub App token and expose it as BOT_TOKEN env
runs:
  using: composite
  steps:
    - name: Create GitHub App Token
      id: app
      # Create a GitHub App token
      # https://github.com/marketplace/actions/create-github-app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.ST_BOT_APP_ID }}
        private-key: ${{ secrets.ST_BOT_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: Write App Token -> env.BOT_TOKEN
      run: echo "BOT_TOKEN=${{ steps.app.outputs.token }}" >> $GITHUB_ENV
      shell: bash
