name: Build and Publish Release (Staging)

on:
  push:
    branches:
      - staging

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build and package with pkg
      run: |
        npm install -g pkg
        npm run pkg

    - name: Upload binaries to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        tag_name: ci-staging
        name: Continuous Release (Staging)
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
