name: PR Lint & Test

on:
  pull_request:
    branches: [ "staging", "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - name: Install test dependencies
      run: npm ci --prefix tests
    - name: Run unit tests
      run: npm run test:unit --prefix tests
